{{- if .Values.global.singleNamespace.create }}
{{- if .Values.singleNamespace.createNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.global.singleNamespace.name }}"
  labels:
    quarks.cloudfoundry.org/monitored: {{ template "quarks-job.monitoredID" . }}
    quarks.cloudfoundry.org/qjob-service-account: "{{ .Values.persistOutputClusterRole.name }}"
{{- end }}

{{- if .Values.singleNamespace.createAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.persistOutputClusterRole.name }}"
  namespace: "{{ .Values.global.singleNamespace.name }}"
secrets:
  - name: "{{ .Values.persistOutputClusterRole.name }}-token-secret"

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: "{{ .Values.persistOutputClusterRole.name }}-token-secret"
  namespace: "{{ .Values.global.singleNamespace.name }}"
  annotations:
    kubernetes.io/service-account.name: "{{ .Values.persistOutputClusterRole.name }}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.persistOutputClusterRole.name }}"
  namespace: "{{ .Values.global.singleNamespace.name }}"
subjects:
- kind: ServiceAccount
  name: "{{ .Values.persistOutputClusterRole.name }}"
roleRef:
  kind: ClusterRole
  name: "{{ .Values.persistOutputClusterRole.name }}"
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
